### ISSUE TITLE
Code Request for Generating GT images -- The reconstruction approach

### ISSUE THREAD

**Issue by Kshitizbansal** [ChristianSchuessler/Sparse-Array-Radar-Imaging#1]
Hi,

Thanks for the awesome work and code release. Could you also share the code that was used to process the GT images. Specifically, the matched filter based reconstruction approach. Thanks.

-Kshitiz

**Comment by ChristianSchuessler** [comment]
Hi, 

okay I uploaded the matched filter implementation.

Kind regards,

Christian
