### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by daydreamer2023** [ChristianSchuessler/Sparse-Array-Radar-Imaging#2]
Thank you so much for sharing your outstanding work.
Are there plans to share datasets? Or just share simulation datasets?

**Comment by ChristianSchuessler** [comment]
Our group plans to publish measurement datasets, which should be compatible with this approach. I will update this issue as soon as it happens.

**Comment by daydreamer2023** [comment]
This sounds great!
However, I think the simulation data may be more convenient, because the measured data is usually very large and the download will be very slow.
The generation script of simulation data will be more convenient, especially some parameter adjustment and quantitative analysis can be done flexibly.

**Comment by ChristianSchuessler** [comment]
Sorry, but at the moment we do not plan to release the simulator code.

**Comment by daydreamer2023** [comment]
Anyway, thanks for the great work you do, and for sharing the training code, which will be useful to other researchers.
I wish you success in your research and more excellent work.
